### ISSUE TITLE
might need to change the FROM (base) on the dockerfile

### ISSUE THREAD

**Issue by davew-msft** [vaggeliskls/windows-in-docker-container#1]
First off, excellent solution.  Love it.  

It took me a bit to get it going, getting the ip6_tables errors you write about in some of your blog posts.  I tried everything imaginable and then I noticed in one of the posts you are using `FROM ubuntu:18.04` and in another you are using 20.04.  Well, I'm using ubuntu 22 on the host so I changed the dockerfile to `FROM ubuntu:22.04` and everything magically started working.  

Posting this here merely to help the next person.  No clue why that worked or if it's reproducible, but it worked for me.  

Again, excellent solution.

**Comment by vaggeliskls** [comment]
Thank you so much for your valuable feedback!

I truly appreciate your input as it helps improve the project. 
Based on your suggestions, 
I've gone ahead and opened a PR (#2 ) to update the Ubuntu version to 22.04. 

Please feel free to review the changes and share any thoughts or additional feedback you may have.
