### ISSUE TITLE
executable 'modinfo' not found

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [vaggeliskls/windows-in-docker-container#10]
Hi, running this under Ubuntu 22.04, following instructions, I get this error:
```❯ docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED        STATUS                   PORTS                                                                                                                             NAMES
90a3c1a5eaa1   windows-in-docker-container-win10   "/startup.sh /bin/ba…"   4 hours ago    Exited (1) 4 hours ago                                                                                                                                     windows-in-docker-container-win10-1
❯ docker logs 90a3c1a5eaa1
Bringing machine 'default' up with 'libvirt' provider...
The executable 'modinfo' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```
Any advice, please? 

Edit: I have changed the `Dockerfile` towards this image: `peru/windows-10-enterprise-x64-eval`

**Comment by vaggeliskls** [comment]
Hello @MichaelMichaelMichaelMichaelMichael,

Thank you for bringing this issue to our attention.

Upon investigating, I was able to consistently replicate the issue you reported. However, I have found a potential solution which entails the inclusion of `kmod` in the Dockerfile.

I've created and merged a new PR which incorporates this workaround. You should notice the update in the latest version of the code.

It would be greatly helpful if you can pull this update, test it in your environment, and provide your feedback. This will assist me in confirming the effectiveness of the proposed solution and ensure it resolves the issue across different setups.

I appreciate the time and effort you've taken to make us aware of this, as it helps improve the quality and reliability of our project.

Looking forward to hearing back from you soon.
Thanks
