### ISSUE TITLE
exec /startup.sh: no such file or directory

### ISSUE THREAD

**Issue by kelcalegari** [vaggeliskls/windows-in-docker-container#7]
When attempting to run docker compose up, I encountered an error related to the execution of a startup script (startup.sh). The error message states: "exec /startup.sh: no such file or directory". This issue occurred after successfully building the Docker image and creating the necessary network and container.

Steps to Reproduce:

Clone the repository or navigate to the directory containing the docker-compose.yml file.
Run docker compose up.
Expected Behavior:
The Docker container should start successfully and execute the startup.sh script as part of its initialization process.

Actual Behavior:
The following error is encountered:
```
win10-1  | exec /startup.sh: no such file or directory
win10-1 exited with code 1
```
Additional Information:

The startup.sh script is included in the root directory of the Docker context and is correctly copied to the root directory (/) of the container during the build process.
The permissions for the startup.sh script are set correctly to allow execution within the container.
Manually accessing the container and verifying the presence and permissions of the startup.sh script did not reveal any issues.

´´´
docker compose up
[+] Building 4.4s (18/18) FINISHED                                                                                                             docker:default
[win10 internal] load build definition from Dockerfile                                                                                               0.0s
transferring dockerfile: 1.09kB                                                                                                                   0.0s
[win10] resolve image config for docker.io/docker/dockerfile:1.5                                                                                     1.3s
  [win10 auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                   0.0s
 CACHED [win10] docker-image://docker.io/docker/dockerfile:1.5@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                0.0s
 [win10 internal] load .dockerignore                                                                                                                  0.0s
 transferring context: 2B                                                                                                                          0.0s
 [win10 internal] load metadata for docker.io/library/ubuntu:22.04                                                                                    2.7s
[win10 auth] library/ubuntu:pull token for registry-1.docker.io                                                                                      0.0s
 [win10 1/9] FROM docker.io/library/ubuntu:22.04@sha256:e9569c25505f33ff72e88b2990887c9dcf230f23259da296eb814fc2b41af999                              0.0s
[win10 internal] load build context                                                                                                                  0.0s 
 transferring context: 63B                                                                                                                         0.0s 
CACHED [win10 2/9] RUN apt-get update -y &&     apt-get install -y     qemu-kvm     build-essential     libvirt-daemon-system     libvirt-dev     o  0.0s 
CACHED [win10 3/9] RUN wget https://releases.hashicorp.com/vagrant/2.4.0/vagrant_2.4.0-1_amd64.deb &&     apt install ./vagrant_2.4.0-1_amd64.deb &  0.0s 
CACHED [win10 4/9] RUN vagrant plugin install vagrant-libvirt                                                                                        0.0s 
CACHED [win10 5/9] RUN vagrant box add --provider libvirt peru/windows-server-2022-standard-x64-eval &&     vagrant init peru/windows-server-2022-s  0.0s 
CACHED [win10 6/9] COPY Vagrantfile /Vagrantfile.tmp                                                                                                 0.0s 
CACHED [win10 7/9] RUN rm -rf /Vagrantfile                                                                                                           0.0s 
CACHED [win10 8/9] COPY startup.sh /                                                                                                                 0.0s 
CACHED [win10 9/9] RUN chmod +x startup.sh                                                                                                           0.0s 
[win10] exporting to image                                                                                                                           0.0s 
 exporting layers                                                                                                                                  0.0s 
writing image sha256:743b19d51465b5dddba673dbab2c0e1154c2522dc37a63c747f0da8f30f1d181                                                             0.0s 
 naming to docker.io/library/dockervm-win10                                                                                                        0.0s 
[+] Running 2/2
 ✔ Network dockervm_default    Created                                                                                                                   0.1s 
 ✔ Container dockervm-win10-1  Created                                                                                                                   0.1s 
Attaching to win10-1
win10-1  | exec /startup.sh: no such file or directory
win10-1 exited with code 1
´´´

**Comment by vaggeliskls** [comment]
Hi @kelcalegari,

Thanks for bringing this to our attention and for your valuable feedback.

I attempted to recreate the issue you're experiencing, but without success. To better help you, may I please have the following information:

1. Your Docker version
2. Your Operating System

It could be possible that the issue arose from local modifications made prior to building. If you've made changes in your local environment, I would recommend taking the following steps:

Try to rebuild and run the image using the following command: `docker compose up --build`
Alternatively, you can use the following image directly to circumvent the issue:

`ghcr.io/vaggeliskls/windows-in-docker-container:latest`

> For usage, please refer to the example provided in the Readme.md file

This will hopefully help us diagnose the issue better. Looking forward to your response.


Best Regards
